title: Page
preset: page
fields:
  metaDescription:
    label: Meta Description
    type: textarea
    help: SEO description for search results
  text:
    label: Body
    type: textarea
    size: large
